language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.14"
  - "7.10"
  - "8.11"
  - "9.10"
sudo: false
cache:
  directories:
    - node_modules
